lexer grammar MilvusJdbcLexer;

SHOW: S H O W;
COLLECTIONS: C O L L E C T I O N S;
COLLECTION: C O L L E C T I O N;
DESCRIBE: D E S C R I B E;
DESC: D E S C;
CREATE: C R E A T E;
DROP: D R O P;
DIMENSION: D I M E N S I O N;
INSERT: I N S E R T;
INTO: I N T O;
VALUES: V A L U E S;
DELETE: D E L E T E;
FROM: F R O M;
WHERE: W H E R E;
SELECT: S E L E C T;
ORDER: O R D E R;
BY: B Y;
LIMIT: L I M I T;

DATABASE: D A T A B A S E;
DATABASES: D A T A B A S E S;
TABLE: T A B L E;
TABLES: T A B L E S;
IF: I F;
EXISTS: E X I S T S;
PRIMARY: P R I M A R Y;
KEY: K E Y;
DEFAULT: D E F A U L T;
COMMENT: C O M M E N T;
AUTO_ID: A U T O '_' I D;
PARTITION: P A R T I T I O N;
PARTITIONS: P A R T I T I O N S;
INDEX: I N D E X;
INDEXES: I N D E X E S;
ON: O N;
USING: U S I N G;
WITH: W I T H;
ALIAS: A L I A S;
FOR: F O R;
ALTER: A L T E R;
SET: S E T;
PROPERTIES: P R O P E R T I E S;
PASSWORD: P A S S W O R D;
USE: U S E;
USER: U S E R;
USERS: U S E R S;
ROLE: R O L E;
ROLES: R O L E S;
GRANT: G R A N T;
GRANTS: G R A N T S;
REVOKE: R E V O K E;
PRIVILEGE: P R I V I L E G E;
GLOBAL: G L O B A L;
TO: T O;
LOAD: L O A D;
RELEASE: R E L E A S E;
FLUSH: F L U S H;
COUNT: C O U N T;
UPSERT: U P S E R T;
UPDATE: U P D A T E;
RENAME: R E N A M E;
PROGRESS: P R O G R E S S;
LOADING: L O A D I N G;
OF: O F;
OFFSET: O F F S E T;
ASC: A S C;
BOOL: B O O L;
INT8: I N T '8';
INT16: I N T '16';
INT32: I N T '32';
INT64: I N T '64';
FLOAT: F L O A T;
DOUBLE: D O U B L E;
VARCHAR: V A R C H A R;
JSON: J S O N;
FLOAT_VECTOR: F L O A T '_' V E C T O R;
BINARY_VECTOR: B I N A R Y '_' V E C T O R;
FLOAT16_VECTOR: F L O A T '16' '_' V E C T O R;
BFLOAT16_VECTOR: B F L O A T '16' '_' V E C T O R;
SPARSE_FLOAT_VECTOR: S P A R S E '_' F L O A T '_' V E C T O R;
ARRAY: A R R A Y;
METRIC: M E T R I C '_' T Y P E;
PARAMS: P A R A M S;
ROUND_DECIMAL: R O U N D '_' D E C I M A L;
CONSISTENCY_LEVEL: C O N S I S T E N C Y '_' L E V E L;
VECTOR: V E C T O R;
TRUE: T R U E;
FALSE: F A L S E;
NULL: N U L L;
AND: A N D | '&&';
OR: O R | '||';
IN: I N;
LIKE: L I K E;
IS: I S;
NOT: N O T;

OPEN_PAREN: '(';
CLOSE_PAREN: ')';
OPEN_BRACKET: '[';
CLOSE_BRACKET: ']';
COMMA: ',';
SEMI: ';';
STAR: '*';
EQUALS: '=';
EQ: '==';
NE: '!=' | '<>';
GTE: '>=';
LTE: '<=';
GT: '>';
LT: '<';
LT_MINUS_GT: '<->';
LT_EQ_GT: '<=>';
LT_HASH_GT: '<#>';
PLUS: '+';
MINUS: '-';
SLASH: '/';
MOD: '%';
ARG: '?';

STRING_LITERAL
    : '\'' ( ~['\\\r\n] | '\\' . | '\'\'' )* '\''
    | '"'  ( ~["\\\r\n] | '\\' . | '""'   )* '"'
    ;

FLOAT_LITERAL
    : [0-9]+ '.' [0-9]* ([eE] [+-]? [0-9]+)?
    | '.' [0-9]+ ([eE] [+-]? [0-9]+)?
    | [0-9]+ [eE] [+-]? [0-9]+
    ;
INTEGER: [0-9]+;
IDENTIFIER: BACKTICK_ID | QUOTED_ID | [a-zA-Z_] [a-zA-Z0-9_.-]*;

SingleLineComment: '--' ~[\r\n]* -> skip;
MultiLineComment: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;

fragment BACKTICK_ID: '`' ~'`'+ '`';
fragment QUOTED_ID: '"' (~["\\\r\n] | '\\' . | '""')* '"';
fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
